title: Ali Hussain
email: allawi.hussain@gmail.com
markdown: kramdown
description: >-
  Hello, I'm Ali! I'm a software engineer based out of San Francisco.
baseurl:
url: "https://www.allawihussain.com"
github_username: alihussain5
navigation:
  - url: '/'
    title: 'About'
    id: 'about'
  - url: '/readings'
    title: 'Readings'
    id: 'readings'
  - url: '/writings'
    title: 'Writings'
    id: 'writings'