title: Ali Hussain
email: allawi.hussain@gmail.com
markdown: kramdown
theme: minima
description: >-
  Hello, I'm Ali! I'm a software engineer based out of San Francisco.
url: "https://www.allawihussain.com"
github_username: alihussain5

